### ISSUE TITLE
delete 'btest' PyPi package

### ISSUE THREAD

**Issue by jsiwek** [DanielJDufour/beryl#3]
Hi, it looks like you never really used the name 'btest' for this repository.  If that's right, would you be willing to delete the 'btest' package from PyPi (https://pypi.python.org/pypi/btest) ?

We've been using our own tool called 'btest' (https://github.com/bro/btest) for quite a while, but are just now getting around to uploading to PyPi and would be great if we could keep the name consistent there.

**Comment by DanielJDufour** [comment]
Done.  I removed btest from PyPi.  Congrats on your contribution to PyPi :)

**Comment by jsiwek** [comment]
Thanks.
